# Configuration for the Plant Genetics Explorer

# --- General App Settings ---
app_title: "🌱 Plant Genetics Explorer (Configured v2.1)"
app_description: |
  Explore open genetic databases and analyze (mock) gene-trait relationships in plants.
  **Note:** This is a simplified demonstrator using configuration from YAML.
  Sample files generated are saved to the configured data directory.

# --- Data Directory ---
data_directory: "genetic_data_output" # You can change this path

# --- Database Acquisition Guide Settings ---
database_options:
  - "NCBI (SRA, GenBank, RefSeq)"
  - "Ensembl Plants"
  - "Phytozome (JGI)"
  - "The Arabidopsis Information Resource (TAIR)" # Example of adding another
default_database: "Ensembl Plants"

# --- Mock Gene Data (can be extensive) ---
# You can move the entire MOCK_GENE_DATA dictionary here.
# For brevity in this example, I'll show a shortened version.
# Ensure the structure matches the Python dictionary.
mock_gene_data:
  AT1G01010:
    name: "Photosystem II subunit P (YAML)"
    description: "Essential for the assembly and stability of photosystem II."
    traits: ["Photosynthesis Efficiency", "Growth Rate"]
    expression_levels: {leaf: 105, root: 25, flower: 65} # Slightly different values
    go_terms: ["GO:0009521", "GO:0015979"]
    ncbi_gene_id: "839502"
    ensembl_plants_id: "AT1G01010"
  AT1G01020:
    name: "F-box family protein (YAML)"
    description: "Involved in protein degradation pathways, affecting development."
    traits: ["Flowering Time", "Stress Response"]
    expression_levels: {leaf: 55, root: 75, flower: 95}
    go_terms: ["GO:0003674", "GO:0008150"]
    ncbi_gene_id: "839503"
    ensembl_plants_id: "AT1G01020"
  AT1G01030:
    name: "Heat shock protein 70 (YAML)"
    description: "Chaperone protein involved in response to heat and other stresses."
    traits: ["Stress Response", "Protein Folding"]
    expression_levels: {leaf: 35, root: 85, flower: 45}
    go_terms: ["GO:0006950", "GO:0003774"]
    ncbi_gene_id: "839504"
    ensembl_plants_id: "AT1G01030"
  AT2G01010:
    name: "Auxin response factor (YAML)"
    description: "Transcription factor mediating auxin signaling."
    traits: ["Root Development", "Growth Rate"]
    expression_levels: {leaf: 45, root: 125, flower: 55}
    go_terms: ["GO:0009733", "GO:0003677"]
    ncbi_gene_id: "824100"
    ensembl_plants_id: "AT2G01010"

# You could add more configuration options here if needed, e.g., plot colors, etc.