# Configuration for the Plant Genetics Explorer (Live Data Focus v3.0)

# --- General App Settings ---
app_title: "🌱 Plant Genetics Explorer (Live NCBI Data)"
app_description: |
  Explore live gene data fetched directly from NCBI.
  **Note:** Ensure your Entrez email is correctly set for NCBI access.
  Fetched files are saved to the configured data directory.

# --- NCBI Entrez Email ---
# IMPORTANT: Replace with your actual email address for reliable NCBI access.
entrez_email: "Williambfreeforlife@gmail.com" 

# --- Data Directory ---
data_directory: "genetic_data_output_live" # You can change this path

# --- Database Acquisition Guide Settings ---
# This section provides informational links to various databases.
database_options:
  - "NCBI (SRA, GenBank, RefSeq)"
  - "Ensembl Plants"
  - "Phytozome (JGI)"
  - "The Arabidopsis Information Resource (TAIR)"
default_database: "NCBI (SRA, GenBank, RefSeq)"

# --- NCBI Search Settings ---
# Species options for contextual keyword search on NCBI tab.
ncbi_plant_species_options:
  - "Arabidopsis thaliana"
  - "Oryza sativa Japonica Group" # Rice
  - "Zea mays" # Maize / Corn
  - "Glycine max" # Soybean
  - "Solanum lycopersicum" # Tomato
  - "Triticum aestivum" # Wheat
  - "Vitis vinifera" # Grape
  - "Populus trichocarpa" # Poplar
  - "Medicago truncatula"
  # Add more common plant species as needed

# --- NCBI Search Defaults ---